### ISSUE TITLE
Standard Vite Tab Icon

### ISSUE THREAD

**Issue by julianzangl** [HTL-EveryTask/everytask-web#2]
Endlich kann ich einen Issue machen :)

Das Tab Icon ist noch das Standard Vite Logo und nicht unseres.
Außerdem steht dort "Vite App" und nicht sowas wie "Homepage"

**Comment by Nekonyx13** [comment]
![image](https://user-images.githubusercontent.com/60986851/202861711-83a103c8-76d1-4cd3-ad85-a165226b903a.png)

skill issue meinerseits
