### ISSUE TITLE
Login: Umlaute in Mail

### ISSUE THREAD

**Issue by julianzangl** [HTL-EveryTask/everytask-web#3]
Bro, you cannot have those crazy austrian 'umlaute' in your mail?!?!

How to reproduce:
step 1) Enter following mail oida in Login: hörandl@everytask.at
step 2) profit

![image](https://user-images.githubusercontent.com/75028879/219961537-18cacf94-3d17-4317-bbcd-3224fdb71a91.png)

![image](https://user-images.githubusercontent.com/75028879/219961557-e1b6fcb9-bc80-486e-864a-beac50e0dc75.png)

**Comment by Nekonyx13** [comment]
Thank you for your concern. However, it is not usually common practice to use Umlauts in E-mail Addresses.

As shown in this image, not even GitHub allows for Umlauts in their E-Mail Addresses :)
![image](https://user-images.githubusercontent.com/60986851/221418625-3a8032e9-30ce-4e12-b6fc-c77f3c5d1f58.png)
