### ISSUE TITLE
Search for all Appointments

### ISSUE THREAD

**Issue by julianzangl** [HTL-EveryTask/everytask-web#4]
Search is not working properly for all appointments:

![image](https://user-images.githubusercontent.com/75028879/221371862-2a466c4a-32a1-43d7-a7a5-9894a007d3da.png)

Cant find "Custom Themes erstellen"

**Comment by Nekonyx13** [comment]
That is because "Custom Themes erstellen" is listed as a task, not an appointment.

Currently, the Calendar List View only supports viewing appointments and is still waiting to be further discussed with our design professional. Thank u for the issue tho
