### ISSUE TITLE
User to Group add broken if user doesn't exist

### ISSUE THREAD

**Issue by Lizardl** [HTL-EveryTask/everytask-web#6]
![image](https://user-images.githubusercontent.com/61635380/226189486-2fcb0ccb-306c-418d-baea-e3d4d9ea6fc0.png)

Ich habe nur Enter gedrückt :(

**Comment by Lizardl** [comment]
I think I broke everything 
![image](https://user-images.githubusercontent.com/61635380/226189573-2618b3fa-01e5-4b07-897a-23dd4d0648b6.png)

**Comment by Nekonyx13** [comment]
ähhhhhhhhh kannst du bitte erklären wie ich das reproduzieren kann

**Comment by Lizardl** [comment]
you write ahjukdghakjhdakuwh und dann enter

**Comment by Nekonyx13** [comment]
fixed in sprint-7-redesign branch
