### ISSUE TITLE
Bug bei Änderung eines importierten Task 

### ISSUE THREAD

**Issue by Lizardl** [HTL-EveryTask/everytask-web#9]
Ich habe den Namen geändert und update gedrückt. Es wurde zwar nichts verändert, aber ich kann nicht mehr klicken (siehe Video)

https://user-images.githubusercontent.com/61635380/227038522-a811e9e9-a93e-4d13-b726-e3e47e60be2c.mp4

**Comment by Nekonyx13** [comment]
Made imported tasks uneditable now
